PUT http://localhost:3000/user/1/ban/1  HTTP/1.1
Content-Type: application/json
Authorization: Bearer 2



go build ./cmd/webapi/
./webapi

sudo bash ./open-npm.sh
npm run build-embed
exit
go build -tags webui ./cmd/webapi/


sudo bash ./open-npm.sh
npm run dev

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